version: "3"
services:
  mysql:
    container_name: "mysql-training-borneo"
    build:
      context: .
      dockerfile: DockerfileMysql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=training

    ports:
      - "3306:3306"

    volumes:
      - ./db:/var/lib/mysql

    networks:
      training_net:
        ipv4_address: 12.12.12.2

  php:
    container_name: "php-training-borneo"
    build:
      context: .
      dockerfile: DockerfilePhp

    volumes:
      - .:/usr/share/nginx/html/test

    networks:
      training_net:
        ipv4_address: 12.12.12.3

  nginx:
    container_name: "nginx-training-borneo"
    build:
      context: .
      dockerfile: DockerfileNginx

    ports:
      - "80:80"

    volumes:
      - ./dockerConfig:/etc/nginx/conf.d
      - .:/usr/share/nginx/html/test

    networks:
      training_net:
        ipv4_address: 12.12.12.4

networks:
  training_net:
    ipam:
      driver: default
      config:
        - subnet: 12.12.12.0/24
